const exercises = [
  "Push-up",
  "Squat",
  "Lunge",
  "Deadlift",
  "Bench Press",
  "Pull-up",
  "Rows",
  "Overhead Press",
  "Bicep Curl",
  "Plank",
  "Dumbbell Fly",
  "Side Lateral Raise",
  "Tricep Extension",
  "Calf Raise",
  "Hammer Curl",
  "Leg Press",
  "Incline Bench Press",
  "Dumbbell Row",
  "Skull Crusher",
  "Russian Twist",
  "Barbell Curl",
  "Hamstring Curl",
  "Shoulder Press",
  "Leg Extension",
  "Dips",
  "Seated Cable Row",
  "Leg Curl",
  "Barbell Squat",
  "Reverse Fly",
  "Romanian Deadlift",
  "Hammer Strength Chest Press",
  "Close Grip Bench Press",
  "Barbell Deadlift",
  "Hammer Strength Row",
  "Rear Delt Fly",
  "Barbell Bent-Over Row",
  "Standing Calf Raise",
  "Dumbbell Pullover",
  "Incline Dumbbell Fly",
  "Seated Leg Curl",
  "Cable Crossover",
  "Seated Dumbbell Shoulder Press",
  "Machine Shoulder Press",
  "Incline Dumbbell Bench Press",
  "Machine Chest Press",
  "Incline Bench Cable Fly",
  "One-Arm Dumbbell Row",
  "Lateral Pulldown",
  "Reverse Grip Pulldown",
  "Hammer Curl to Press",
  "Smith Machine Squat",
  "Hammer Strength Leg Press",
  "Seated Calf Raise",
  "Hack Squat",
  "Roman Chair Leg Raise",
  "Cable Bicep Curl",
  "Preacher Curl",
  "Close-Grip Pulldown",
  "Reverse Grip Cable Row",
  "Overhead Tricep Extension",
  "Dumbbell Lunges",
  "Cable Rope Tricep Pushdown",
  "Barbell Hip Thrust",
  "Seated Leg Press",
  "Lat Pulldown",
  "Barbell Bench Press",
  "Single-Arm Dumbbell Press",
  "Cable Lateral Raise",
  "Incline Dumbbell Curl",
  "Cable Hammer Curl",
  "Dumbbell Shoulder Shrug",
  "Cable Seated Row",
  "Leg Extension Machine",
  "Barbell Skullcrusher",
  "Cable Rear Delt Fly",
  "Seated Barbell Military Press",
  "Seated Leg Extension",
  "Incline Bench Dumbbell Curl",
  "Cable Tricep Kickback",
  "Smith Machine Inverted Row",
  "Cable Face Pull",
  "Machine Chest Fly",
  "Seated Dumbbell Curl",
  "Reverse Grip Barbell Row",
  "Lying Leg Curl",
  "Dumbbell Shoulder Press",
  "Barbell Bent Over Row",
  "Standing Dumbbell Tricep Extension",
  "Cable Bicep Hammer Curl",
  "Lateral Box Jump",
  "Push Press",
  "Incline Dumbbell Press",
  "Smith Machine Calf Raise",
  "Cable Tricep Overhead Extension",
  "Barbell Romanian Deadlift",
  "Dumbbell Incline Curl",
  "Cable Reverse Fly",
  "Seated Cable Bicep Curl",
  "Leg Press Machine Calf Raise",
  "Barbell Front Squat",
  "Inverted Row",
  "Dumbbell Step-up",
  "Cable Single Arm Tricep Extension",
  "Decline Dumbbell Press",
  "Seated Cable Row Machine",
  "One Arm Dumbbell Row",
  "Seated Dumbbell Tricep Kickback",
  "Dumbbell Bench Press",
  "Cable Chest Fly",
  "Seated Leg Press Machine",
  "Dumbbell Lateral Raise",
  "Cable Tricep Pushdown",
  "Barbell Overhead Press",
  "Arnold Press",
  "Dumbbell Lying Rear Lateral Raise",
  "Standing Military Press",
  "Dumbbell Upright Row",
  "Dumbbell Front Raise",
  "Dumbbell Shrugs",
];

export default exercises;
